---

- name: Add APT key
  apt_key: keyserver={{mongodb_apt_key_url}} id="{{mongodb_apt_key_id}}"

- name: Add APT repository
  apt_repository: repo="{{mongodb_repository}}" update_cache=yes

- name: Install MongoDB package
  apt: name={{item}} state=present
  with_items:
    - mongodb-org=3.2.0
    - mongodb-org-shell=3.2.0

- name: Configure mongodb
  template: src=mongod.conf.j2 dest=/etc/mongod.conf
  notify: restart mongo