---

- name: Add APT key
  apt_key: keyserver={{mongodb_apt_key_url}} id="{{mongodb_apt_key_id}}"

- name: Add APT repository
  apt_repository: repo="{{mongodb_repository}}" update_cache=yes

- name: Install MongoDB package
  apt: name={{item}} state=present
  with_items:
    - mongodb-org

- name: Configure mongodb
  lineinfile: dest=/etc/mongod.conf regexp="^bind_ip" line="bind_ip=0.0.0.0"
  notify: restart mongo