- name : install Nginx
  apt : name=nginx state=present
  notify : start nginx

- file: path=/etc/nginx/sites-available state=directory

- copy: src=templates/defaultNginx dest=/etc/nginx/sites-available/default
  notify: restart nginx