---

mongodb_package: mongodb-org
mongodb_apt_key_url: keyserver.ubuntu.com
mongodb_apt_key_id: EA312927 
mongodb_repository: deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse
mongodb_conf_bind_ip: 0.0.0.0
mongodb_daemon_name: "{{ 'mongod' if ('mongodb-org' in mongodb_package) else 'mongodb' }}"